# Setup for USB connection to WDF-6M200-3, a sensor of Dynpick.
#
# This shell script must be executed in super user privileges.

echo 'Setup udev rule for Dynpick force torque sensor.'
echo 'NOTE: this shell script must be executed in super user privileges.'

# Install udev, device management tool.
apt install libudev-dev

mkdir -p /etc/udev/rules.d

echo `# This rule is auto-generated by the shell script of dynpick-force-torque-sensor crate.` >> /etc/udev/rules.d/80-wacoh.rules
echo `# See https://github.com/Amelia10007/dynpick-force-torque-sensor-rs in detail.` >> /etc/udev/rules.d/80-wacoh.rules
echo `# Note that the following rule may be specific to WDF-6M200-3, one of the Dynpick force torque sensors.` >> /etc/udev/rules.d/80-wacoh.rules
echo 'ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666"' >> /etc/udev/rules.d/80-wacoh.rules

# udev must be rebooted because we modified the rule.
service udev restart
